### ISSUE TITLE
is device tree is correct ?

### ISSUE THREAD

**Issue by vipCodeError** [on7/android_device_o7prolte-uncommon#1]
device tree is not detected in lunch command .
here is how is goes 
`g123_vipulj@instance-1:~/android/system$ source ./build/envsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/lge/hammerhead/vendorsetup.sh
including device/samsung/android_device_o7prolte-uncommon/vendorsetup.sh
including device/samsung/o7prolte/vendorsetup.sh
including vendor/cm/vendorsetup.sh
including sdk/bash_completion/adb.bash
including vendor/cm/bash_completion/git.bash
including vendor/cm/bash_completion/repo.bash

after breakfast command is show this error
** Don't have a product spec for: 'lineage_o7prolte'
** Do you have the right repo manifest?
`
I have placed right files in right directory and still showing this error.

**Comment by androidlover5842** [comment]
rename android_device_o7prolte-uncommon folder to o7prolte
